---
- hosts: all
  tasks:
    - name: Initialize Configuration System
      ansible.builtin.import_role:
        name: config_secrets
      become: true

    - name: System Setup
      ansible.builtin.import_role:
        name: system
      become: true
    