---
- hosts: all
  gather_facts: yes
  become: false

  tasks:
    - name: Test basic apt update
      apt:
        update_cache: yes
        cache_valid_time: 3600
      become: true

    - name: Test package installation
      apt:
        name:
          - curl
          - wget
        state: present
      become: true

    - name: Display success
      debug:
        msg: "✅ Basic system test successful"