---
- hosts: all
  gather_facts: yes
  become: false

  tasks:
    - name: Test basic connectivity
      debug:
        msg: "✅ Ansible connectivity successful"

    - name: Check current user
      command: whoami
      register: current_user
      changed_when: false

    - name: Display current user
      debug:
        msg: "Running as user: {{ current_user.stdout }}"

    - name: Check if sudo is available
      command: sudo -n true
      register: sudo_check
      failed_when: false
      changed_when: false

    - name: Display sudo status
      debug:
        msg: |
          Sudo status: {{ 'Available (passwordless)' if sudo_check.rc == 0 else 'Requires password' }}
