---
- name: Get list of non-root users with home directories
  shell: |
    getent passwd | awk -F: '$3 >= 1000 && $3 < 65534 && $6 ~ /^\/home\// { print $1 ":" $5 ":" $6 }' | sort
  register: existing_users
  changed_when: false

- name: Parse existing users
  set_fact:
    user_list: "{{ existing_users.stdout_lines | map('split', ':') | list }}"
  when: existing_users.stdout_lines | length > 0

- name: Display available users
  debug:
    msg: |

      Available System Users
      ─────────────────────────────────────────────────
      {% for user in user_list %}
      {{ loop.index }}. {{ user[0] }}{% if user[1] and user[1] != '' %} ({{ user[1] }}){% endif %} → {{ user[2] }}
      {% endfor %}

      Options: Enter number (1-{{ user_list | length }}), username, or 'new'
  when: user_list is defined and user_list | length > 0

- name: Use provided rootless_user_selection or prompt
  block:
    - name: Prompt for user selection when not provided
      pause:
        prompt: |

          🔧 Rootless User Selection
          ─────────────────────────────────────────────────
          Choose an option:

          • Enter a number (1-{{ user_list | length }}) to select an existing user
          • Enter a username directly
          • Enter 'new' to create a new user

          Your choice
      register: user_choice_prompt
      when: rootless_user_selection is not defined or rootless_user_selection == ""

    - name: Set user choice from variable or prompt
      set_fact:
        user_choice: "{{ rootless_user_selection if (rootless_user_selection is defined and rootless_user_selection != '') else user_choice_prompt.user_input }}"

  when: user_list is defined and user_list | length > 0

- name: Handle no existing users case
  block:
    - name: Use provided new_user_name or prompt
      pause:
        prompt: |

          Create New User
          ─────────────────────────────────────────────────
          No existing non-root users found on this system.

          Enter username for new user
      register: new_user_prompt
      when: new_user_name is not defined or new_user_name == ""

    - name: Set new username
      set_fact:
        user_choice: "new"
        new_username: "{{ new_user_name if (new_user_name is defined and new_user_name != '') else new_user_prompt.user_input }}"

  when: user_list is not defined or user_list | length == 0

- name: Process user selection
  block:
    - name: Handle numeric selection
      set_fact:
        rootless_user: "{{ user_list[user_choice | int - 1][0] }}"
      when:
        - user_choice | regex_search('^\d+$')
        - user_choice | int > 0
        - user_choice | int <= (user_list | length)

    - name: Handle direct username
      set_fact:
        rootless_user: "{{ user_choice }}"
      when:
        - user_choice != 'new'
        - not (user_choice | regex_search('^\d+$'))
        - user_list | selectattr('0', 'equalto', user_choice) | list | length > 0

    - name: Handle new user creation
      include_tasks: create_new_user.yml
      when: user_choice == 'new'

- name: Validate user selection result
  fail:
    msg: |
      Invalid user selection: {{ user_choice }}
      Please provide a valid username, number, or 'new'
  when: rootless_user is not defined
