---
- name: Check if Docker is installed
  command: docker --version
  register: docker_check
  failed_when: false
  changed_when: false

- name: Install Docker if not present
  include_tasks: docker/install.yml
  when: docker_check.rc != 0

- name: Handle existing Docker services
  include_tasks: docker/handle_services.yml
  when: docker_check.rc == 0
