---
- name: Create apt keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Add Docker GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"

- name: Get system architecture
  command: dpkg --print-architecture
  register: system_arch
  changed_when: false

- name: Get distribution codename
  command: lsb_release -cs
  register: dist_codename
  changed_when: false

- name: Detect OS family and set repository
  set_fact:
    docker_repo_url: "{{ 'https://download.docker.com/linux/ubuntu' if ansible_distribution == 'Ubuntu' else 'https://download.docker.com/linux/debian' }}"
    docker_gpg_url: "{{ 'https://download.docker.com/linux/ubuntu/gpg' if ansible_distribution == 'Ubuntu' else 'https://download.docker.com/linux/debian/gpg' }}"

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch={{ system_arch.stdout }} signed-by=/etc/apt/keyrings/docker.asc] {{ docker_repo_url }} {{ dist_codename.stdout }} stable"
    filename: docker
    state: present

- name: Update apt cache after adding Docker repo
  apt:
    update_cache: yes

- name: Install Docker packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Display Docker installation complete
  debug:
    msg: "Docker has been successfully installed"
