---
- name: Download Docker installation script
  get_url:
    url: https://get.docker.com/
    dest: /tmp/get-docker.sh
    mode: "0755"

- name: Install Docker using official script
  shell: CHANNEL=stable sh /tmp/get-docker.sh
  args:
    creates: /usr/bin/docker
  become: true

- name: Clean up installation script
  file:
    path: /tmp/get-docker.sh
    state: absent

- name: Display Docker installation complete
  debug:
    msg: "Docker has been successfully installed using official script"
