---
# Task to store an encrypted secret
# Usage: include_tasks with secret_name and secret_data

- name: Validate required variables
  assert:
    that:
      - secret_name is defined
      - secret_data is defined
    fail_msg: "secret_name and secret_data must be defined"

- name: Store secret file (will be encrypted)
  copy:
    content: "{{ secret_data | to_nice_yaml }}"
    dest: "{{ uncommonfix_secrets_dir }}/{{ secret_name }}.yml"
    mode: "{{ secrets_file_mode }}"
  become: false

- name: Encrypt secret file with ansible-vault
  shell: |
    ansible-vault encrypt "{{ uncommonfix_secrets_dir }}/{{ secret_name }}.yml"
  args:
    creates: "{{ uncommonfix_secrets_dir }}/{{ secret_name }}.yml"
  environment:
    ANSIBLE_VAULT_PASSWORD_FILE: "{{ vault_password_file | default(omit) }}"
  when: encrypt_secrets | default(true)
