---
- name: Initialize service configuration
  set_fact:
    service_config: {}

- name: Process configuration template
  include_tasks: process_config_field.yml
  vars:
    field_path: "{{ item.key }}"
    field_config: "{{ item.value }}"
    parent_path: ""
  loop: "{{ config_template | dict2items }}"

- name: Display configuration summary
  debug:
    msg: |
      Configuration Summary for {{ service_metadata.name }}:
      {{ service_config | to_nice_json }}
