---
- name: Find all service directories in configs
  find:
    paths: "{{ role_path }}/configs"
    file_type: directory
  register: service_dirs

- name: Load service metadata files
  include_vars:
    file: "{{ item.path }}/service.yml"
    name: "service_{{ item.path | basename }}"
  loop: "{{ service_dirs.files }}"

- name: Build available services list
  set_fact:
    available_services: "{{ available_services | default([]) + [service_info] }}"
  loop: "{{ service_dirs.files }}"
  vars:
    service_name: "{{ item.path | basename }}"
    service_info: "{{ vars['service_' + service_name] | combine({'service_name': service_name}) }}"

- name: Group services by category
  set_fact:
    services_by_category: "{{ services_by_category | default({}) | combine({item.category: (services_by_category[item.category] | default([])) + [item]}) }}"
  loop: "{{ available_services }}"

- name: Display discovered services summary
  debug:
    msg: "Discovered {{ available_services | length }} services across {{ services_by_category.keys() | length }} categories"
  when: available_services is defined
