---
- name: Set current field name
  set_fact:
    current_field_name: "{{ field_path }}"

- name: Parse field definition
  set_fact:
    field_type: "{{ field_config.split('|')[0] if '|' in field_config else field_config }}"
    field_default: "{{ field_config.split('|')[1:] | join('|') if '|' in field_config else '' }}"

- name: Get existing variable value
  set_fact:
    existing_value: "{{ lookup('vars', current_field_name, default='') }}"

- name: Handle fixed type
  set_fact:
    field_value: "{{ field_default }}"
  when: field_type == "fixed"

- name: Handle non-fixed types with existing values
  set_fact:
    field_value: "{{ existing_value }}"
  when: field_type != "fixed" and existing_value != ""

- name: Handle non-fixed types with default values and no existing value
  set_fact:
    field_value: "{{ field_default }}"
  when: field_type != "fixed" and existing_value == "" and field_default != ""

- name: Prompt for value when needed
  include_tasks: prompt_for_value.yml
  when: field_type != "fixed" and existing_value == "" and field_default == ""

- name: Set configuration value
  set_fact:
    service_config: "{{ service_config | combine({current_field_name: field_value}) }}"
  when: field_value is defined
