---
- name: Generate prompt message
  set_fact:
    prompt_message: "{{ prompt_messages[field_type] | default('Enter ' + current_field_name) }}"
  vars:
    prompt_messages:
      string: "Enter {{ current_field_name }}"
      password: "Enter {{ current_field_name }} (hidden input)"
      boolean: "Enable {{ current_field_name }}? (true/false)"
      ip: "Enter {{ current_field_name }} (IPv4 or IPv6 address)"
      email: "Enter {{ current_field_name }} (email address)"
      url: "Enter {{ current_field_name }} (URL)"
      port: "Enter {{ current_field_name }} (port number 1-65535)"

- name: Prompt for password field
  pause:
    prompt: "{{ prompt_message }}"
    echo: false
  register: user_input
  when: field_type == "password"

- name: Prompt for non-password field
  pause:
    prompt: "{{ prompt_message }}"
  register: user_input
  when: field_type != "password"

- name: Validate input
  fail:
    msg: "{{ validation_messages[field_type] | default('Invalid input') }}"
  vars:
    validation_messages:
      string: "Value cannot be empty"
      password: "Password cannot be empty"
      boolean: "Please enter: true or false"
      ip: "Please enter a valid IPv4 or IPv6 address"
      email: "Please enter a valid email address"
      url: "Please enter a valid URL (http:// or https://)"
      port: "Please enter a valid port number (1-65535)"
  when: >
    user_input is defined and (
      (field_type == "string" and user_input.user_input == "") or
      (field_type == "password" and user_input.user_input == "") or
      (field_type == "boolean" and user_input.user_input not in ["true", "false", "yes", "no", "y", "n"]) or
      (field_type == "email" and not (user_input.user_input | regex_search('^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'))) or
      (field_type == "port" and not (user_input.user_input | regex_search('^[0-9]+$') and user_input.user_input | int >= 1 and user_input.user_input | int <= 65535))
    )

- name: Normalize boolean values
  set_fact:
    normalized_input: "{{ 'true' if user_input.user_input.lower() in ['true', 'yes', 'y'] else 'false' }}"
  when: field_type == "boolean" and user_input is defined

- name: Set field value
  set_fact:
    field_value: "{{ normalized_input if (field_type == 'boolean' and normalized_input is defined) else user_input.user_input }}"
  when: user_input is defined
